### ISSUE TITLE
Please update pandoc.exe

### ISSUE THREAD

**Issue by arisima** [martinwiboe/PandocTasks#1]
Hi,
I absolutely love your PandocTasks, I am using this from VisualStudio NuGetPackage.

Just one request.
Could you please update the version of the pandoc.exe that is included in PandocTasks?
It seems that the reference "--reference-docx" is not working in the current version.

Thank you in advance.
arisima

**Comment by martinwiboe** [comment]
Hi @arisima 

Glad to hear you're using the software :)
I'll update Pandoc and push a new version. Will get around to it later this week.

/Martin

**Comment by arisima** [comment]
Hi Martin,
Thank you for the reply :)
Around when can you push the new version? 
Rergards,
arisima

**Comment by martinwiboe** [comment]
Hi @arisima 

I've uploaded a new version of the package :)
I haven't tested it thoroughly. If you find any issues, I'd be happy if you'd open a new issue.

Regards
Martin
